logo: /static/img/legal-title-conveyancing-logo-rgb.jpg
name: Legal Title Conveyancing
phone: 0432 901 751
email: hello@legaltitle.com.au
address: |-
  C1 Rear,  209-213 Victoria Road

  Gladesville NSW 2111
hero: /static/img/tierra-mallorca-jxi2ap8dtnc-unsplash.jpg
body: >-
  With over 25 years of collected experience Legal Title can take the stress out of buying, selling or refinancing property. Based in Gladesville in the north of Sydney we service all of NSW.

  
  Our licensed conveyancers have a passion for real estate and will be there to help throughout the process.
author: Exeter Web Services
url: https://exeterwebservices.com.au
