logo: /static/img/legal-title-conveyancing-logo-rgb.jpg
name: Legal Title Conveyancing
phone: 0432 901 751
email: hello@legaltitle.com.au
address: |-
  C1 Rear,  209-213 Victoria Road

  Gladesville NSW 2111
hero: /static/img/hero.webp
body: >-
  With over 25 years of collective experience Legal Title can take the stress
  out of buying, selling or refinancing property.


  Based in Gladesville in the north of Sydney we service all of NSW.


  As Licensed Conveyancers have a passion for property and welcome the opportunity to make all your property transactions as stress free as possible.  One of the main ways we do this is by always being available to speak with you and address any concerns and find solutions. 


  Do you find yourself speaking to automated robots whenever you call any company, government department, insurer or bank?  It is so frustrating keying in numbers, waiting on hold – that will not be the case when you call Kerrie or Andrea at Legal Title Conveyancing.  We answer our mobiles and if we are speaking to another client, you can leave a message and we will return your call.   Communication is the key point of difference between Legal Title Conveyancing and other firms – we aim to be there for you any time including after hours and weekends.


  ![](https://ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif)
author: Exeter Web Services
url: https://exeterwebservices.com.au
