logo: /static/img/new-logo.png
name: Legal Title Conveyancing
phone: 0432 901 751
email: hello@legaltitle.com.au
address: |-
  C1 Rear,  209-213 Victoria Road

  Gladesville NSW 2111
hero: /static/img/bridge.webp
body: >-
  With over 30 years of collective experience Legal Title can take the stress
  out of:-


  * Purchase or Sale of Residential or Commercial property, including:-

    * Torrens Title;
    * Strata Title;
    * Company Title;
    * Old System Title;
  * Off the Plan matters

  * Purchase or Sale of a Business.

  * Commercial / Retail Leases acting for both a Lessor  or Lessee

  * Mortgages


  Based in Gladesville in the north of Sydney we service all of NSW.


  As Licensed Conveyancers have a passion for property and welcome the opportunity to make all your property transactions as stress free as possible.  One of the main ways we do this is by always being available to speak with you and address any concerns and find solutions.


  When you call Kerrie or Andrea you will not be answered by an automated robot, as is so commonplace today.  We answer our mobiles and if we are speaking to another client, you can leave a message and we will return your call.  


  Communication is the key point of difference between Legal Title Conveyancing and other firms – we aim to be there for you any time including after hours and weekends and home/ workplace visits if you cannot come to us.
author: Exeter Web Services
url: https://exeterwebservices.com.au
